name: stack-lint-extra-deps
description: Install and run stack-lint-extra-deps

inputs:
  version:
    description: Version of the tool to install
    required: true
    default: 1.2.0.0
  arguments:
    description: Arguments to pass. Must be shell-escaped. Default is none.
    required: false
  executable:
    description: Name of stack-lint-extra-deps executable
    required: false
    default: stack-lint-extra-deps
  no-install:
    description: |
      Skip installing the tool. Instead, the executable will be expected
      to be installed and on PATH already.
    required: false
    default: false

outputs: {}

runs:
  using: composite
  steps:
    - if: ${{ inputs.no-install != 'true' }}
      uses: pbrisbin/setup-tool-action@v1
      with:
        name: stack-lint-extra-deps
        version: ${{ inputs.version }}
        url: "https://github.com/freckle/{name}/releases/download/v{version}/{name}-{arch}-{os}.{ext}"
        subdir: "{name}"
        os-darwin: osx
        arch-x64: x86_64

    - shell: bash
      run: |
        ${{inputs.executable}} ${{ inputs.arguments }}
      env:
        LOG_COLOR: always
        LOG_CONCURRENCY: 1
