name: stack-lint-extra-deps

# Format: {EPOCH}.{MAJOR}.{MINOR}.{PATCH}
#
# {MAJOR}.{MINOR}.{PATCH} will be automatically set by semantic-relase, the
# manually-set {EPOCH} will be respected. If changing {EPOCH}, also change
# tagFormat in .releaserc.yaml.
version: 1.0.0.0

extra-doc-files:
  - README.md
  - CHANGELOG.md

extra-source-files:
  - test/examples/lts-18.18.yaml

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings
  - TypeApplications
  - DuplicateRecordFields

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-role-annotations
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe
  - -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - Blammo
    - Glob
    - aeson
    - bytestring
    - containers
    - errors
    - extra
    - filepath
    - html-conduit
    - http-conduit
    - http-types
    - lens
    - optparse-applicative
    - relude
    - semigroups
    - shellwords
    - text
    - typed-process
    - unliftio
    - unliftio-core
    - xml-conduit
    - yaml-marked

executables:
  stack-lint-extra-deps:
    source-dirs: app
    main: Main.hs
    dependencies:
      - Blammo
      - stack-lint-extra-deps
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Blammo
      - aeson
      - bytestring
      - containers
      - extra
      - file-embed
      - lens
      - hspec
      - stack-lint-extra-deps
      - text
      - yaml-marked
