#!/usr/bin/env bash

COMMIT=$(curl "https://api.github.com/repos/commercialhaskell/all-cabal-hashes/commits/hackage" | jq --raw-output '.sha')

HASH=$(nix-prefetch-url "https://github.com/commercialhaskell/all-cabal-hashes/archive/${COMMIT}.tar.gz")

echo $COMMIT

echo $HASH
